### PR TITLE
Fix build for newer Boost versions

### PR DESCRIPTION
**Pull request by robert7k**
Build with boost-1.79.0 fails:

```
/tmp/SkypeExport-1.4.0/work/SkypeExport-1.4.0/src/SkypeExport/model/skypeparser_parsing.cpp:935:68: error: ‘next’ is not a member of ‘boost’
  935 |                                                         if( boost::next( identities_it ) != tokens.end() ){ thisEvent.asXHTML << ", "; } // appended after every element except the last one
```

This fixes it.

### CODE REVIEW

**Comment by sthoduka** [comment]
@robert7k Thanks for the PR. I noticed that the header file you added is already included on line 22 of the same file. Was that the only change that fixed the issue?

I tested with Boost 1.71, and the current version of the code builds without a problem.

**Comment by robert7k** [comment]
You're right, I oversaw that. I had the patch prepared for release 1.4.0 where this isn't present. So nothing to fix, but maybe time for a release ;-)
